# Generated by Django 4.0.6 on 2022-08-01 11:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='catagorymodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='categoryName', unique=True),
        ),
    ]
