# Generated by Django 4.0.6 on 2022-08-01 11:43

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_catagorymodel_options_alter_catagorymodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleImage', models.ImageField(upload_to='article_images')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('editDate', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aricles', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='article', to='blog.catagorymodel')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'Article',
            },
        ),
    ]
