# Generated by Django 4.0.6 on 2022-08-01 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
